export enum AliasDeployedContracts {
  UtilsUpgradeable_Proxy = 'UtilsUpgradeable_Proxy',
  UtilsUpgradeable_Implementation = 'UtilsUpgradeable_Implementation',
  ProxyAdmin = 'ProxyAdmin',
  BribeUpgradeable_Implementation = 'BribeUpgradeable_Implementation',
  VotingEscrowUpgradeableV1_2_Implementation = 'VotingEscrowUpgradeableV1_2_Implementation',
  VotingEscrowUpgradeableV1_2_Proxy = 'VotingEscrowUpgradeableV1_2_Proxy',
  VoterUpgradeableV1_2_Implementation = 'VoterUpgradeableV1_2_Implementation',
  Pair_Implementation = 'Pair_Implementation',
  UniswapV2PartialRouter = 'UniswapV2PartialRouter',
  VoterUpgradeable_Implementation = 'VoterUpgradeable_Implementation',
  VoterUpgradeable_Proxy = 'VoterUpgradeable_Proxy',
  VotingEscrowUpgradeable_Implementation = 'VotingEscrowUpgradeable_Implementation',
  VeArtProxyUpgradeable_Implementation = 'VeArtProxyUpgradeable_Implementation',
  VeArtProxyUpgradeable_Proxy = 'VeArtProxyUpgradeable_Proxy',
  RouterV2 = 'RouterV2',
  PairAPIUpgradeable_Implementation = 'PairAPIUpgradeable_Implementation',
  PairAPIUpgradeable_Proxy = 'PairAPIUpgradeable_Proxy',
  RewardAPIUpgradeable_Implementation = 'RewardAPIUpgradeable_Implementation',
  RewardAPIUpgradeable_Proxy = 'RewardAPIUpgradeable_Proxy',
  CompoundVeFNXManagedNFTStrategyUpgradeable_Implementation = 'CompoundVeFNXManagedNFTStrategyUpgradeable_Implementation',
  GaugeUpgradeable_Implementation = 'GaugeUpgradeable_Implementation',
  PairFactoryUpgradeable_Implementation = 'PairFactoryUpgradeable_Implementation',
  PairFactoryUpgradeable_Proxy = 'PairFactoryUpgradeable_Proxy',
  FeesVaultFactoryUpgradeable_Implementation = 'FeesVaultFactoryUpgradeable_Implementation',
  FeesVaultFactoryUpgradeable_Proxy = 'FeesVaultFactoryUpgradeable_Proxy',
  RouterV2PathProviderUpgradeable_Implementation = 'RouterV2PathProviderUpgradeable_Implementation',
  RouterV2PathProviderUpgradeable_Proxy = 'RouterV2PathProviderUpgradeable_Proxy',
  CompoundVeFNXManagedNFTStrategyFactoryUpgradeable_Implementation = 'CompoundVeFNXManagedNFTStrategyFactoryUpgradeable_Implementation',
  CompoundVeFNXManagedNFTStrategyFactoryUpgradeable_Proxy = 'CompoundVeFNXManagedNFTStrategyFactoryUpgradeable_Proxy',
  ManagedNFTManagerUpgradeable_Implementation = 'ManagedNFTManagerUpgradeable_Implementation',
  ManagedNFTManagerUpgradeable_Proxy = 'ManagedNFTManagerUpgradeable_Proxy',
  BlastRebasingTokensGovernorUpgradeable_Implementation = 'BlastRebasingTokensGovernorUpgradeable_Implementation',
  BlastRebasingTokensGovernorUpgradeable_Proxy = 'BlastRebasingTokensGovernorUpgradeable_Proxy',
  MerklGaugeMiddleman = 'MerklGaugeMiddleman',
  BribeFactoryUpgradeable_Implementation = 'BribeFactoryUpgradeable_Implementation',
  BribeFactoryUpgradeable_Proxy = 'BribeFactoryUpgradeable_Proxy',
  VeNFTAPIUpgradeable_Implementation = 'VeNFTAPIUpgradeable_Implementation',
  VeNFTAPIUpgradeable_Proxy = 'VeNFTAPIUpgradeable_Proxy',
  PerpetualsTradersRewarderUpgradeable_Implementation = 'PerpetualsTradersRewarderUpgradeable_Implementation',
  PerpetualsTradersRewarderUpgradeable_Proxy = 'PerpetualsTradersRewarderUpgradeable_Proxy',
  VeBoostUpgradeable_Implementation = 'VeBoostUpgradeable_Implementation',
  VeBoostUpgradeable_Proxy = 'VeBoostUpgradeable_Proxy',
  MinterUpgradeable_Implementation = 'MinterUpgradeable_Implementation',
  MinterUpgradeable_Proxy = 'MinterUpgradeable_Proxy',
  VeFnxSplitMerklAidropUpgradeable_Implementation = 'VeFnxSplitMerklAidropUpgradeable_Implementation',
  VeFnxSplitMerklAidropUpgradeable_Proxy = 'VeFnxSplitMerklAidropUpgradeable_Proxy',
  RFenix = 'RFenix',
  FenixRaiseUpgradeable_Implementation = 'FenixRaiseUpgradeable_Implementation',
  FenixRaiseUpgradeable_Proxy = 'FenixRaiseUpgradeable_Proxy',
  FeesVaultUpgradeable_Implementation = 'FeesVaultUpgradeable_Implementation',
  PerpetualsGaugeUpgradeable_Implementation = 'PerpetualsGaugeUpgradeable_Implementation',
  PerpetualsGaugeUpgradeable_Proxy = 'PerpetualsGaugeUpgradeable_Proxy',
  VeFnxDistributorUpgradeable_Implementation = 'VeFnxDistributorUpgradeable_Implementation',
  VeFnxDistributorUpgradeable_Proxy = 'VeFnxDistributorUpgradeable_Proxy',
  SingelTokenVirtualRewarderUpgradeable_Implementation = 'SingelTokenVirtualRewarderUpgradeable_Implementation',
  GaugeFactoryUpgradeable_Implementation = 'GaugeFactoryUpgradeable_Implementation',
  GaugeFactoryUpgradeable_Proxy_1 = 'GaugeFactoryUpgradeable_Proxy_1',
  GaugeFactoryUpgradeable_Proxy_2 = 'GaugeFactoryUpgradeable_Proxy_2',
  GaugeFactoryUpgradeable_Proxy_3 = 'GaugeFactoryUpgradeable_Proxy_3',
  AlgebraFNXPriceProviderUpgradeable_Implementation = 'AlgebraFNXPriceProviderUpgradeable_Implementation',
  AlgebraFNXPriceProviderUpgradeable_Proxy = 'AlgebraFNXPriceProviderUpgradeable_Proxy',
  Fenix = 'Fenix',
  BlastGovernorUpgradeable_Implementation = 'BlastGovernorUpgradeable_Implementation',
  BlastGovernorUpgradeable_Proxy = 'BlastGovernorUpgradeable_Proxy',
  MDCBlastMock = 'MDCBlastMock',
}

enum ThirdPart {
  Blast = 'IBlastFull',
}
enum ContractsInstanceName {
  UtilsUpgradeable = 'UtilsUpgradeable',
  ProxyAdmin = 'ProxyAdmin',
  BribeUpgradeable = 'BribeUpgradeable',
  VotingEscrowUpgradeableV1_2 = 'VotingEscrowUpgradeableV1_2',
  VoterUpgradeableV1_2 = 'VoterUpgradeableV1_2',
  Pair = 'Pair',
  UniswapV2PartialRouter = 'UniswapV2PartialRouter',
  VoterUpgradeable = 'VoterUpgradeable',
  VotingEscrowUpgradeable = 'VotingEscrowUpgradeable',
  VeArtProxyUpgradeable = 'VeArtProxyUpgradeable',
  RouterV2 = 'RouterV2',
  PairAPIUpgradeable = 'PairAPIUpgradeable',
  RewardAPIUpgradeable = 'RewardAPIUpgradeable',
  CompoundVeFNXManagedNFTStrategyUpgradeable = 'CompoundVeFNXManagedNFTStrategyUpgradeable',
  GaugeUpgradeable = 'GaugeUpgradeable',
  PairFactoryUpgradeable = 'PairFactoryUpgradeable',
  FeesVaultFactoryUpgradeable = 'FeesVaultFactoryUpgradeable',
  RouterV2PathProviderUpgradeable = 'RouterV2PathProviderUpgradeable',
  CompoundVeFNXManagedNFTStrategyFactoryUpgradeable = 'CompoundVeFNXManagedNFTStrategyFactoryUpgradeable',
  ManagedNFTManagerUpgradeable = 'ManagedNFTManagerUpgradeable',
  BlastRebasingTokensGovernorUpgradeable = 'BlastRebasingTokensGovernorUpgradeable',
  MerklGaugeMiddleman = 'MerklGaugeMiddleman',
  BribeFactoryUpgradeable = 'BribeFactoryUpgradeable',
  VeNFTAPIUpgradeable = 'VeNFTAPIUpgradeable',
  PerpetualsTradersRewarderUpgradeable = 'PerpetualsTradersRewarderUpgradeable',
  VeBoostUpgradeable = 'VeBoostUpgradeable',
  MinterUpgradeable = 'MinterUpgradeable',
  VeFnxSplitMerklAidropUpgradeable = 'VeFnxSplitMerklAidropUpgradeable',
  RFenix = 'RFenix',
  FenixRaiseUpgradeable = 'FenixRaiseUpgradeable',
  FeesVaultUpgradeable = 'FeesVaultUpgradeable',
  PerpetualsGaugeUpgradeable = 'PerpetualsGaugeUpgradeable',
  VeFnxDistributorUpgradeable = 'VeFnxDistributorUpgradeable',
  SingelTokenVirtualRewarderUpgradeable = 'SingelTokenVirtualRewarderUpgradeable',
  GaugeFactoryUpgradeable = 'GaugeFactoryUpgradeable',
  AlgebraFNXPriceProviderUpgradeable = 'AlgebraFNXPriceProviderUpgradeable',
  Fenix = 'Fenix',
  TransparentUpgradeableProxy = 'TransparentUpgradeableProxy',
  BlastGovernorUpgradeable = 'BlastGovernorUpgradeable',
}

export const InstanceName = {
  ...ContractsInstanceName,
  ...ThirdPart,
};

export type InstanceName = ContractsInstanceName;
